version: '3'
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: devlopment
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
    - NODE_ENV=devlopment
    command: npm run dev